<?php
$labels = array();
$labels['mh_title'] = 'أبرز ما في الرسالة';
$labels['mh_matches'] = 'أعواد الثقاب';
$labels['mh_color'] = 'اللون';
$labels['mh_delete'] = 'حذف';
$labels['mh_delete_description'] = 'احذف هذا السطر';
$labels['mh_add'] = 'إضافة صف';
$labels['mh_add_description'] = 'أضف صفاً إضافياً أسفل هذا الصف';
$labels['deleteconfirm'] = 'هل تريد حقاً حذف هذه القاعدة؟';
$labels['headererror'] = 'خطأ في قاعدة الرسائل';
$labels['inputempty'] = 'واحدة أو أكثر من أعواد الثقاب فارغة';
$labels['invalidcolor'] = 'لون غير صالح';
?>
