<?php
$labels = array();
$labels['mh_title'] = 'বাৰ্তাৰ মুখ্য অংশ';
$labels['mh_matches'] = 'মেল খোৱা';
$labels['mh_color'] = 'ৰং';
$labels['mh_delete'] = 'মচি পেলাওক';
$labels['mh_delete_description'] = 'এই শাৰীটো মচি পেলাওক';
$labels['mh_add'] = 'শাৰী যোগ কৰক';
$labels['mh_add_description'] = 'এই শাৰীৰ তলত এটা অতিৰিক্ত শাৰী যোগ কৰক।';
$labels['deleteconfirm'] = 'আপুনি সঁচাকৈ এই নিয়মটো মচিব বিচাৰে নেকি?';
$labels['headererror'] = 'বাৰ্তাৰ নিয়মত ত্ৰুটি';
$labels['inputempty'] = 'আপোনাৰ এটা বা ততোধিক মেচ খালী আছে।';
$labels['invalidcolor'] = 'অসিদ্ধ ৰং';
?>
