<?php
$labels = array();
$labels['mh_title'] = 'Mesajın əsas məqamları';
$labels['mh_matches'] = 'uyğun gəlir';
$labels['mh_color'] = 'rəng';
$labels['mh_delete'] = 'sil';
$labels['mh_delete_description'] = 'Bu sətri silin';
$labels['mh_add'] = 'sətir əlavə et';
$labels['mh_add_description'] = 'Bu sətrin altına əlavə bir sətr əlavə edin';
$labels['deleteconfirm'] = 'Həqiqətən bu qaydanı silmək istəyirsinizmi?';
$labels['headererror'] = 'Mesaj qaydasında səhv';
$labels['inputempty'] = 'Sizin bir və ya bir neçə uyğunluğunuz boşdur';
$labels['invalidcolor'] = 'Etibarsız rəng';
?>
