<?php
$labels = array();
$labels['mh_title'] = 'Галоўныя моманты паведамлення';
$labels['mh_matches'] = 'адпавядае';
$labels['mh_color'] = 'колер';
$labels['mh_delete'] = 'выдаліць';
$labels['mh_delete_description'] = 'Выдаліць гэты радок';
$labels['mh_add'] = 'дадаць радок';
$labels['mh_add_description'] = 'Дадайце дадатковы радок пад гэтым радком';
$labels['deleteconfirm'] = 'Вы сапраўды хочаце выдаліць гэтае правіла?';
$labels['headererror'] = 'Памылка ў правіле паведамленняў';
$labels['inputempty'] = 'Адзін ці некалькі вашых матчаў пустыя';
$labels['invalidcolor'] = 'Няправільны колер';
?>
