<?php
$labels = array();
$labels['mh_title'] = 'Акценти на съобщението';
$labels['mh_matches'] = 'съвпада с';
$labels['mh_color'] = 'цвят';
$labels['mh_delete'] = 'изтриване на';
$labels['mh_delete_description'] = 'Изтрийте този ред';
$labels['mh_add'] = 'добавяне на ред';
$labels['mh_add_description'] = 'Добавяне на допълнителен ред под този ред';
$labels['deleteconfirm'] = 'Наистина ли искате да изтриете това правило?';
$labels['headererror'] = 'Грешка в правилото за съобщения';
$labels['inputempty'] = 'Едно или повече от съвпаденията ви са празни';
$labels['invalidcolor'] = 'Невалиден цвят';
?>
