<?php
$labels = array();
$labels['mh_title'] = 'বার্তার প্রধান অংশ';
$labels['mh_matches'] = 'মিলছে';
$labels['mh_color'] = 'রঙ';
$labels['mh_delete'] = 'মুছুন';
$labels['mh_delete_description'] = 'এই লাইনটি মুছুন';
$labels['mh_add'] = 'সারি যোগ করুন';
$labels['mh_add_description'] = 'এই সারিটির নিচে একটি অতিরিক্ত সারি যোগ করুন।';
$labels['deleteconfirm'] = 'আপনি কি সত্যিই এই নিয়মটি মুছে ফেলতে চান?';
$labels['headererror'] = 'বার্তা নিয়মে ত্রুটি';
$labels['inputempty'] = 'আপনার একটি বা একাধিক ম্যাচ ফাঁকা আছে।';
$labels['invalidcolor'] = 'অবৈধ রঙ';
?>
