<?php
$labels = array();
$labels['mh_title'] = 'Poentoù pouezus ar gemennadenn';
$labels['mh_matches'] = 'kenglotadurioù';
$labels['mh_color'] = 'liv';
$labels['mh_delete'] = 'Dilemel';
$labels['mh_delete_description'] = 'Dilemel al linenn-mañ';
$labels['mh_add'] = 'Ouzhpennañ ur renkennad';
$labels['mh_add_description'] = 'Ouzhpennañ ur renkennad ouzhpenn dindan ar renkennad-mañ';
$labels['deleteconfirm'] = 'Ha fellout a ra deoc\'h da vat diverkañ ar reolenn-mañ?';
$labels['headererror'] = 'Fazi er reolenn gemennadenn';
$labels['inputempty'] = 'Unan pe meur a hini eus ho kenglotadurioù zo goullo.';
$labels['invalidcolor'] = 'Liv direizh';
?>
