<?php
$labels = array();
$labels['mh_title'] = 'Izdvojeno iz poruke';
$labels['mh_matches'] = 'utakmice';
$labels['mh_color'] = 'boja';
$labels['mh_delete'] = 'izbriši';
$labels['mh_delete_description'] = 'Obriši ovaj redak';
$labels['mh_add'] = 'Dodaj redak';
$labels['mh_add_description'] = 'Dodajte dodatni red ispod ovog reda';
$labels['deleteconfirm'] = 'Želite li zaista izbrisati ovo pravilo?';
$labels['headererror'] = 'Greška u pravilu poruke';
$labels['inputempty'] = 'Jedan ili više vaših mečeva su prazni';
$labels['invalidcolor'] = 'Neispravna boja';
?>
