<?php
$labels = array();
$labels['mh_title'] = 'Punts destacats del missatge';
$labels['mh_matches'] = 'partits';
$labels['mh_color'] = 'color';
$labels['mh_delete'] = 'esborrar';
$labels['mh_delete_description'] = 'Suprimeix aquesta línia';
$labels['mh_add'] = 'afegir fila';
$labels['mh_add_description'] = 'Afegeix una fila extra sota aquesta fila.';
$labels['deleteconfirm'] = 'Realment vols eliminar aquesta regla?';
$labels['headererror'] = 'Error a la regla de missatges';
$labels['inputempty'] = 'Un o més dels teus encaixos estan buits';
$labels['invalidcolor'] = 'Color invàlid';
?>
