<?php
$labels = array();
$labels['mh_title'] = 'Nejdůležitější zprávy';
$labels['mh_matches'] = 'odpovídá';
$labels['mh_color'] = 'barva';
$labels['mh_delete'] = 'smazat';
$labels['mh_delete_description'] = 'Vymažte tento řádek';
$labels['mh_add'] = 'přidat řádek';
$labels['mh_add_description'] = 'Přidání dalšího řádku pod tento řádek';
$labels['deleteconfirm'] = 'Opravdu chcete toto pravidlo odstranit?';
$labels['headererror'] = 'Chyba v pravidle pro zasílání zpráv';
$labels['inputempty'] = 'Jedna nebo více vašich zápalek je prázdná';
$labels['invalidcolor'] = 'Neplatná barva';
?>
