<?php
$labels = array();
$labels['mh_title'] = 'Uchafbwyntiau\'r Neges';
$labels['mh_matches'] = 'gêmiau';
$labels['mh_color'] = 'lliw';
$labels['mh_delete'] = 'dileu';
$labels['mh_delete_description'] = 'Dileu\'r llinell hon';
$labels['mh_add'] = 'Ychwanegu rhes';
$labels['mh_add_description'] = 'Ychwanegwch res ychwanegol o dan y rhes hon.';
$labels['deleteconfirm'] = 'Ydych chi wir eisiau dileu\'r rheol hon?';
$labels['headererror'] = 'Gwall yn y rheol neges';
$labels['inputempty'] = 'Mae un neu fwy o\'ch gemau yn wag';
$labels['invalidcolor'] = 'Lliw annilys';
?>
