<?php
$labels = array();
$labels['mh_title'] = 'Højdepunkter i budskabet';
$labels['mh_matches'] = 'tændstikker';
$labels['mh_color'] = 'farve';
$labels['mh_delete'] = 'slette';
$labels['mh_delete_description'] = 'Slet denne linje';
$labels['mh_add'] = 'tilføj række';
$labels['mh_add_description'] = 'Tilføj en ekstra række under denne række';
$labels['deleteconfirm'] = 'Vil du virkelig slette denne regel?';
$labels['headererror'] = 'Fejl i meddelelsesregel';
$labels['inputempty'] = 'Et eller flere af dine matches er tomme';
$labels['invalidcolor'] = 'Ugyldig farve';
?>
