<?php
$labels = array();
$labels['mh_title'] = 'Höhepunkte der Nachricht';
$labels['mh_matches'] = 'passt zu';
$labels['mh_color'] = 'farbe';
$labels['mh_delete'] = 'löschen';
$labels['mh_delete_description'] = 'Diese Zeile löschen';
$labels['mh_add'] = 'zeile hinzufügen';
$labels['mh_add_description'] = 'Fügen Sie eine zusätzliche Zeile unter dieser Zeile ein';
$labels['deleteconfirm'] = 'Wollen Sie diese Regel wirklich streichen?';
$labels['headererror'] = 'Fehler in der Nachrichtenregel';
$labels['inputempty'] = 'Eines oder mehrere Ihrer Streichhölzer sind leer';
$labels['invalidcolor'] = 'Ungültige Farbe';
?>
