<?php
$labels = array();
$labels['mh_title'] = 'Κύρια σημεία του μηνύματος';
$labels['mh_matches'] = 'αγώνες';
$labels['mh_color'] = 'χρώμα';
$labels['mh_delete'] = 'delete';
$labels['mh_delete_description'] = 'Διαγράψτε αυτή τη γραμμή';
$labels['mh_add'] = 'προσθήκη γραμμής';
$labels['mh_add_description'] = 'Προσθέστε μια επιπλέον σειρά κάτω από αυτή τη σειρά';
$labels['deleteconfirm'] = 'Θέλετε πραγματικά να διαγράψετε αυτόν τον κανόνα';
$labels['headererror'] = 'Σφάλμα στον κανόνα μηνύματος';
$labels['inputempty'] = 'Μία ή περισσότερες από τις αντιστοιχίες σας είναι κενές';
$labels['invalidcolor'] = 'Μη έγκυρο χρώμα';
?>
