<?php
$labels = array();
$labels['mh_title'] = 'Elstaraĵoj de la mesaĝo';
$labels['mh_matches'] = 'matĉoj';
$labels['mh_color'] = 'koloro';
$labels['mh_delete'] = 'forigi';
$labels['mh_delete_description'] = 'Forigu ĉi tiun linion';
$labels['mh_add'] = 'aldoni viron';
$labels['mh_add_description'] = 'Aldonu kroman vicon sub ĉi tiu vico.';
$labels['deleteconfirm'] = 'Ĉu vi vere volas forigi ĉi tiun regulon?';
$labels['headererror'] = 'Eraro en mesaĝa regulo';
$labels['inputempty'] = 'Unu aŭ pluraj el viaj matĉoj estas malplenaj.';
$labels['invalidcolor'] = 'Nevalida koloro';
?>
