<?php
$labels = array();
$labels['mh_title'] = 'Aspectos destacados del mensaje';
$labels['mh_matches'] = 'partidos';
$labels['mh_color'] = 'color';
$labels['mh_delete'] = 'eliminar';
$labels['mh_delete_description'] = 'Elimine esta línea';
$labels['mh_add'] = 'agregar fila';
$labels['mh_add_description'] = 'Agregar una fila adicional debajo de esta fila';
$labels['deleteconfirm'] = '¿De verdad quieres eliminar esta regla?';
$labels['headererror'] = 'Error en la regla de mensajes';
$labels['inputempty'] = 'Una o más de tus coincidencias están vacías';
$labels['invalidcolor'] = 'Color no válido';
?>
