<?php
$labels = array();
$labels['mh_title'] = 'Mensaje destacado';
$labels['mh_matches'] = 'coincide con';
$labels['mh_color'] = 'color';
$labels['mh_delete'] = 'borrar';
$labels['mh_delete_description'] = 'Suprima esta línea';
$labels['mh_add'] = 'añadir línea';
$labels['mh_add_description'] = 'Añadir una fila adicional debajo de esta fila';
$labels['deleteconfirm'] = '¿De verdad quieres eliminar esta norma?';
$labels['headererror'] = 'Error en la regla de mensajes';
$labels['inputempty'] = 'Una o más de tus coincidencias están vacías';
$labels['invalidcolor'] = 'Color no válido';
?>
