<?php
$labels = array();
$labels['mh_title'] = 'Sõnumite tipphetked';
$labels['mh_matches'] = 'vastab';
$labels['mh_color'] = 'värv';
$labels['mh_delete'] = 'kustutada';
$labels['mh_delete_description'] = 'Kustuta see rida';
$labels['mh_add'] = 'lisa rida';
$labels['mh_add_description'] = 'Lisage selle rea alla täiendav rida';
$labels['deleteconfirm'] = 'Kas te tõesti soovite selle reegli kustutada?';
$labels['headererror'] = 'Viga sõnumi reeglis';
$labels['inputempty'] = 'Üks või mitu teie mängu on tühi';
$labels['invalidcolor'] = 'Vale värv';
?>
