<?php
$labels = array();
$labels['mh_title'] = 'Mezuaren nabarmendutako puntuak';
$labels['mh_matches'] = 'partiduak';
$labels['mh_color'] = 'kolore';
$labels['mh_delete'] = 'ezabatu';
$labels['mh_delete_description'] = 'Ezabatu lerro hau';
$labels['mh_add'] = 'sartu ilara';
$labels['mh_add_description'] = 'Gehi ezazu lerro bat gehiago lerro honen azpian.';
$labels['deleteconfirm'] = 'Benetan arau hau ezabatu nahi duzu?';
$labels['headererror'] = 'Mezu-arauaren akatsa';
$labels['inputempty'] = 'Zure bat edo gehiago hutsik daude.';
$labels['invalidcolor'] = 'Kolore baliogabea';
?>
