<?php
$labels = array();
$labels['mh_title'] = 'نکات برجسته پیام';
$labels['mh_matches'] = 'مطابقت‌ها';
$labels['mh_color'] = 'رنگ';
$labels['mh_delete'] = 'حذف';
$labels['mh_delete_description'] = 'این خط را حذف کنید';
$labels['mh_add'] = 'افزودن سطر';
$labels['mh_add_description'] = 'یک ردیف اضافی زیر این ردیف اضافه کنید';
$labels['deleteconfirm'] = 'آیا واقعاً می‌خواهید این قانون را حذف کنید؟';
$labels['headererror'] = 'خطا در قاعده پیام';
$labels['inputempty'] = 'یکی یا چند تا از جفت‌های شما خالی هستند';
$labels['invalidcolor'] = 'رنگ نامعتبر';
?>
