<?php
$labels = array();
$labels['mh_title'] = 'Viestin kohokohdat';
$labels['mh_matches'] = 'vastaa';
$labels['mh_color'] = 'väri';
$labels['mh_delete'] = 'poista';
$labels['mh_delete_description'] = 'Poistetaan tämä rivi';
$labels['mh_add'] = 'lisää rivi';
$labels['mh_add_description'] = 'Lisää ylimääräinen rivi tämän rivin alle';
$labels['deleteconfirm'] = 'Haluatko todella poistaa tämän säännön?';
$labels['headererror'] = 'Virhe viestisäännössä';
$labels['inputempty'] = 'Yksi tai useampi otteluistasi on tyhjä';
$labels['invalidcolor'] = 'Väärä väri';
?>
