<?php
$labels = array();
$labels['mh_title'] = 'Points forts du message';
$labels['mh_matches'] = 'correspondances';
$labels['mh_color'] = 'couleur';
$labels['mh_delete'] = 'supprimer';
$labels['mh_delete_description'] = 'Supprimer cette ligne';
$labels['mh_add'] = 'ajouter une ligne';
$labels['mh_add_description'] = 'Ajouter une ligne supplémentaire sous cette ligne';
$labels['deleteconfirm'] = 'Voulez-vous vraiment supprimer cette règle ?';
$labels['headererror'] = 'Erreur dans la règle du message';
$labels['inputempty'] = 'Une ou plusieurs de vos correspondances sont vides';
$labels['invalidcolor'] = 'Couleur non valide';
?>
