<?php
$labels = array();
$labels['mh_title'] = 'Buaicphointí an Teachtaireachta';
$labels['mh_matches'] = 'meaitseanna';
$labels['mh_color'] = 'dath';
$labels['mh_delete'] = 'Scrios';
$labels['mh_delete_description'] = 'Scrios an líne seo';
$labels['mh_add'] = 'Cuir sraith leis';
$labels['mh_add_description'] = 'Cuir sraith bhreise leis faoin sraith seo.';
$labels['deleteconfirm'] = 'Ar mhaith leat an riail seo a scriosadh i ndáiríre?';
$labels['headererror'] = 'Earráid sa riail teachtaireachta';
$labels['inputempty'] = 'Tá ceann amháin nó níos mó de do mheaitseanna folamh';
$labels['invalidcolor'] = 'Dath neamhbhailí';
?>
