<?php
$labels = array();
$labels['mh_title'] = 'Puntos destacados da mensaxe';
$labels['mh_matches'] = 'partidos';
$labels['mh_color'] = 'cor';
$labels['mh_delete'] = 'eliminar';
$labels['mh_delete_description'] = 'Eliminar esta liña';
$labels['mh_add'] = 'engadir fila';
$labels['mh_add_description'] = 'Engade unha fila extra debaixo desta fila';
$labels['deleteconfirm'] = '¿Realmente queres eliminar esta regra?';
$labels['headererror'] = 'Erro na regra de mensaxe';
$labels['inputempty'] = 'Un ou máis dos teus partidos están baleiros';
$labels['invalidcolor'] = 'Cor inválida';
?>
