<?php
$labels = array();
$labels['mh_title'] = 'הודעות חשובות';
$labels['mh_matches'] = 'התאמות';
$labels['mh_color'] = 'צבע';
$labels['mh_delete'] = 'מחק';
$labels['mh_delete_description'] = 'מחק שורה זו';
$labels['mh_add'] = 'הוסף שורה';
$labels['mh_add_description'] = 'הוסף שורה נוספת מתחת לשורה זו';
$labels['deleteconfirm'] = 'האם אתה באמת רוצה למחוק כלל זה?';
$labels['headererror'] = 'שגיאה בכלל הודעה';
$labels['inputempty'] = 'אחד או יותר מההתאמות שלך ריקות';
$labels['invalidcolor'] = 'צבע לא חוקי';
?>
