<?php
$labels = array();
$labels['mh_title'] = 'संदेश की मुख्य बातें';
$labels['mh_matches'] = 'मिलती-जुलती चीज़ें';
$labels['mh_color'] = 'रंग';
$labels['mh_delete'] = 'मिटायें';
$labels['mh_delete_description'] = 'इस पंक्ति को हटाएँ';
$labels['mh_add'] = 'पंक्ति जोड़ें';
$labels['mh_add_description'] = 'इस पंक्ति के नीचे एक अतिरिक्त पंक्ति जोड़ें।';
$labels['deleteconfirm'] = 'क्या आप वास्तव में इस नियम को हटाना चाहते हैं?';
$labels['headererror'] = 'संदेश नियम में त्रुटि';
$labels['inputempty'] = 'आपकी एक या अधिक मिलान खाली हैं।';
$labels['invalidcolor'] = 'अमान्य रंग';
?>
