<?php
$labels = array();
$labels['mh_title'] = 'Üzenet kiemelései';
$labels['mh_matches'] = 'megfelel';
$labels['mh_color'] = 'szín';
$labels['mh_delete'] = 'delete';
$labels['mh_delete_description'] = 'Törölje ezt a sort';
$labels['mh_add'] = 'sor hozzáadása';
$labels['mh_add_description'] = 'Adjon hozzá egy további sort e sor alá';
$labels['deleteconfirm'] = 'Tényleg törölni akarja ezt a szabályt?';
$labels['headererror'] = 'Hiba az üzenetszabályban';
$labels['inputempty'] = 'Egy vagy több találatod üres';
$labels['invalidcolor'] = 'Érvénytelen szín';
?>
