<?php
$labels = array();
$labels['mh_title'] = 'Հաղորդագրության առանցքային կետերը';
$labels['mh_matches'] = 'համապատասխանություններ';
$labels['mh_color'] = 'գույն';
$labels['mh_delete'] = 'ջնջել';
$labels['mh_delete_description'] = 'Հեռացրեք այս տողը';
$labels['mh_add'] = 'Ավելացնել տող';
$labels['mh_add_description'] = 'Ավելացրեք այս տողի տակ մեկ լրացուցիչ տող։';
$labels['deleteconfirm'] = 'Դուք իսկապես ուզում եք ջնջել այս կանոնը՞';
$labels['headererror'] = 'Սխալ հաղորդագրության կանոնում';
$labels['inputempty'] = 'Ձեր մեկ կամ մի քանի համընկնումներ դատարկ են';
$labels['invalidcolor'] = 'Անվավեր գույն';
?>
