<?php
$labels = array();
$labels['mh_title'] = 'Sorotan Pesan';
$labels['mh_matches'] = 'cocok';
$labels['mh_color'] = 'warna';
$labels['mh_delete'] = 'hapus';
$labels['mh_delete_description'] = 'Hapus baris ini';
$labels['mh_add'] = 'tambahkan baris';
$labels['mh_add_description'] = 'Tambahkan baris tambahan di bawah baris ini';
$labels['deleteconfirm'] = 'Apakah Anda benar-benar ingin menghapus aturan ini?';
$labels['headererror'] = 'Kesalahan dalam aturan pesan';
$labels['inputempty'] = 'Satu atau lebih pertandingan Anda kosong';
$labels['invalidcolor'] = 'Warna tidak valid';
?>
