<?php
$labels = array();
$labels['mh_title'] = 'Helstu atriði skilaboða';
$labels['mh_matches'] = 'passar við';
$labels['mh_color'] = 'litur';
$labels['mh_delete'] = 'eyða';
$labels['mh_delete_description'] = 'Eyða þessari línu';
$labels['mh_add'] = 'bæta við röð';
$labels['mh_add_description'] = 'Bættu við einni auka röð undir þessari röð.';
$labels['deleteconfirm'] = 'Viltu virkilega eyða þessari reglu?';
$labels['headererror'] = 'Villa í skilaboðareglunni';
$labels['inputempty'] = 'Einn eða fleiri samsvarar þínum eru tómir';
$labels['invalidcolor'] = 'Ógildur litur';
?>
