<?php
$labels = array();
$labels['mh_title'] = 'Messaggio in evidenza';
$labels['mh_matches'] = 'fiammiferi';
$labels['mh_color'] = 'colore';
$labels['mh_delete'] = 'cancellare';
$labels['mh_delete_description'] = 'Cancellare questa riga';
$labels['mh_add'] = 'aggiungere riga';
$labels['mh_add_description'] = 'Aggiungere una riga in più sotto questa riga';
$labels['deleteconfirm'] = 'Volete davvero eliminare questa regola?';
$labels['headererror'] = 'Errore nella regola dei messaggi';
$labels['inputempty'] = 'Una o più partite sono vuote';
$labels['invalidcolor'] = 'Colore non valido';
?>
