<?php
$labels = array();
$labels['mh_title'] = 'メッセージハイライト';
$labels['mh_matches'] = '試合';
$labels['mh_color'] = 'カラー';
$labels['mh_delete'] = '削除';
$labels['mh_delete_description'] = 'この行を削除する';
$labels['mh_add'] = '行を追加';
$labels['mh_add_description'] = 'この行の下に追加の行を追加する';
$labels['deleteconfirm'] = '本当にこのルールを削除したいのか？';
$labels['headererror'] = 'メッセージルールのエラー';
$labels['inputempty'] = 'マッチの1つ以上が空';
$labels['invalidcolor'] = '無効な色';
?>
