<?php
$labels = array();
$labels['mh_title'] = 'მთავარი მოსაზრებები';
$labels['mh_matches'] = 'შესაბამისობები';
$labels['mh_color'] = 'ფერი';
$labels['mh_delete'] = 'წაშლა';
$labels['mh_delete_description'] = 'შეწაშალეთ ეს სტრიქონი';
$labels['mh_add'] = 'რიგის დამატება';
$labels['mh_add_description'] = 'ამ რიგის ქვეშ დაამატეთ დამატებითი რიგი';
$labels['deleteconfirm'] = 'ნამდვილად გსურთ ამ წესის წაშლა?';
$labels['headererror'] = 'შეცდომა შეტყობინების წესში';
$labels['inputempty'] = 'თქვენი ერთი ან მეტი მატჩი ცარიელია';
$labels['invalidcolor'] = 'არასწორი ფერი';
?>
