<?php
$labels = array();
$labels['mh_title'] = '메시지 하이라이트';
$labels['mh_matches'] = '일치';
$labels['mh_color'] = '색상';
$labels['mh_delete'] = '삭제';
$labels['mh_delete_description'] = '이 줄 삭제';
$labels['mh_add'] = '행 추가';
$labels['mh_add_description'] = '이 행 아래에 추가 행을 추가합니다';
$labels['deleteconfirm'] = '이 규칙을 정말 삭제하시겠습니까?';
$labels['headererror'] = '메시지 규칙에 오류 발생';
$labels['inputempty'] = '하나 이상의 경기가 비어 있습니다';
$labels['invalidcolor'] = '잘못된 색상';
?>
