<?php
$labels = array();
$labels['mh_title'] = 'Botschafts-Highlights';
$labels['mh_matches'] = 'Passen';
$labels['mh_color'] = 'Faarf';
$labels['mh_delete'] = 'Läschen';
$labels['mh_delete_description'] = 'Läscht dës Zeil';
$labels['mh_add'] = 'Rei derbäisetzen';
$labels['mh_add_description'] = 'Füügt eng zousätzlech Rei ënner dëser Rei derbäi.';
$labels['deleteconfirm'] = 'Wëllt Dir dës Regel wierklech läschen?';
$labels['headererror'] = 'Feeler an der Noriicht-Regel';
$labels['inputempty'] = 'Ee oder méi vun äre Matcher sinn eidel.';
$labels['invalidcolor'] = 'Onvalidé Faarf';
?>
