<?php
$labels = array();
$labels['mh_title'] = 'Svarbiausi pranešimai';
$labels['mh_matches'] = 'rungtynės';
$labels['mh_color'] = 'spalva';
$labels['mh_delete'] = 'ištrinti';
$labels['mh_delete_description'] = 'Ištrinkite šią eilutę';
$labels['mh_add'] = 'pridėti eilutę';
$labels['mh_add_description'] = 'Po šia eilute pridėkite papildomą eilutę';
$labels['deleteconfirm'] = 'Ar tikrai norite ištrinti šią taisyklę?';
$labels['headererror'] = 'Klaida pranešimo taisyklėje';
$labels['inputempty'] = 'Vienas ar daugiau jūsų atitikmenų yra tušti';
$labels['invalidcolor'] = 'Netinkama spalva';
?>
