<?php
$labels = array();
$labels['mh_title'] = 'Ziņu izcēlumi';
$labels['mh_matches'] = 'atbilst';
$labels['mh_color'] = 'krāsa';
$labels['mh_delete'] = 'dzēst';
$labels['mh_delete_description'] = 'Dzēst šo rindu';
$labels['mh_add'] = 'pievienot rindu';
$labels['mh_add_description'] = 'Pievienot papildu rindu zem šīs rindas';
$labels['deleteconfirm'] = 'Vai jūs patiešām vēlaties dzēst šo noteikumu?';
$labels['headererror'] = 'Kļūda ziņojuma noteikumā';
$labels['inputempty'] = 'Viens vai vairāki jūsu mači ir tukši';
$labels['invalidcolor'] = 'Nederīga krāsa';
?>
