<?php
$labels = array();
$labels['mh_title'] = 'Истакнати делови од пораката';
$labels['mh_matches'] = 'соодветствува';
$labels['mh_color'] = 'боја';
$labels['mh_delete'] = 'избриши';
$labels['mh_delete_description'] = 'Избришете ја оваа линија';
$labels['mh_add'] = 'додади ред';
$labels['mh_add_description'] = 'Додајте дополнителен ред под овој ред';
$labels['deleteconfirm'] = 'Дали навистина сакате да го избришете ова правило?';
$labels['headererror'] = 'Грешка во правилото за пораки';
$labels['inputempty'] = 'Еден или повеќе од вашите натпревари се празни';
$labels['invalidcolor'] = 'Неважечка боја';
?>
