<?php
$labels = array();
$labels['mh_title'] = 'സന്ദേശത്തിലെ പ്രധാന ഭാഗങ്ങൾ';
$labels['mh_matches'] = 'മത്സരങ്ങൾ';
$labels['mh_color'] = 'നിറം';
$labels['mh_delete'] = 'ഇല്ലാതാക്കുക';
$labels['mh_delete_description'] = 'ഈ വരി ഇല്ലാതാക്കുക';
$labels['mh_add'] = 'നിര ചേർക്കുക';
$labels['mh_add_description'] = 'ഈ വരിക്ക് താഴെ ഒരു അധിക വരി ചേർക്കുക';
$labels['deleteconfirm'] = 'നിങ്ങൾ ഈ നിയമം ശരിക്കും ഇല്ലാതാക്കാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?';
$labels['headererror'] = 'സന്ദേശ നിയമത്തിലെ പിശക്';
$labels['inputempty'] = 'നിങ്ങളുടെ ഒന്നോ അതിലധികമോ മാച്ചുകൾ ഒഴിഞ്ഞതാണ്';
$labels['invalidcolor'] = 'അസാധുവായ നിറം';
?>
