<?php
$labels = array();
$labels['mh_title'] = 'Мессежийн онцлох хэсгүүд';
$labels['mh_matches'] = 'тохирч байна';
$labels['mh_color'] = 'Өнгө';
$labels['mh_delete'] = 'устгах';
$labels['mh_delete_description'] = 'Энэ мөрөө устга';
$labels['mh_add'] = 'Мөр нэмэх';
$labels['mh_add_description'] = 'Энэ мөрний доор нэмэлт мөр нэмнэ үү';
$labels['deleteconfirm'] = 'Та үнэхээр энэ дүрмийг устгахыг хүсч байна уу?';
$labels['headererror'] = 'Мессежийн дүрэмд алдаа';
$labels['inputempty'] = 'Таны нэг буюу хэд хэдэн таарсан зүйл хоосон байна';
$labels['invalidcolor'] = 'Хүчин төгөлдөр бус өнгө';
?>
