<?php
$labels = array();
$labels['mh_title'] = 'संदेश ठळक मुद्दे';
$labels['mh_matches'] = 'जुळते';
$labels['mh_color'] = 'रंग';
$labels['mh_delete'] = 'हटवा';
$labels['mh_delete_description'] = 'ही ओळ हटवा';
$labels['mh_add'] = 'ओळ जोडा';
$labels['mh_add_description'] = 'या ओळीखाली एक अतिरिक्त ओळ जोडा';
$labels['deleteconfirm'] = 'तुम्हाला खरोखर हा नियम हटवायचा आहे का?';
$labels['headererror'] = 'संदेश नियमात त्रुटी';
$labels['inputempty'] = 'तुमच्या एक किंवा अधिक जुळणाऱ्या वस्तू रिकाम्या आहेत';
$labels['invalidcolor'] = 'अमान्य रंग';
?>
