<?php
$labels = array();
$labels['mh_title'] = 'Sorotan Mesej';
$labels['mh_matches'] = 'perlawanan';
$labels['mh_color'] = 'warna';
$labels['mh_delete'] = 'padam';
$labels['mh_delete_description'] = 'Padam baris ini';
$labels['mh_add'] = 'tambah baris';
$labels['mh_add_description'] = 'Tambah satu baris tambahan di bawah baris ini';
$labels['deleteconfirm'] = 'Adakah anda benar-benar mahu memadam peraturan ini?';
$labels['headererror'] = 'Ralat dalam peraturan mesej';
$labels['inputempty'] = 'Satu atau lebih padanan anda kosong';
$labels['invalidcolor'] = 'Warna tidak sah';
?>
