<?php
$labels = array();
$labels['mh_title'] = 'सन्देशका मुख्य अंशहरू';
$labels['mh_matches'] = 'मेल खान्छ';
$labels['mh_color'] = 'रङ';
$labels['mh_delete'] = 'मेटाउनुहोस्';
$labels['mh_delete_description'] = 'यो लाइन मेटाउनुहोस्';
$labels['mh_add'] = 'पङ्क्ति थप्नुहोस्';
$labels['mh_add_description'] = 'यस पङ्क्तिको तल एउटा अतिरिक्त पङ्क्ति थप्नुहोस्।';
$labels['deleteconfirm'] = 'के तपाईं साँच्चै यो नियम मेटाउन चाहनुहुन्छ?';
$labels['headererror'] = 'सन्देश नियममा त्रुटि';
$labels['inputempty'] = 'तपाईंका एक वा बढी मिलानहरू खाली छन्';
$labels['invalidcolor'] = 'अमान्य रङ';
?>
