<?php
$labels = array();
$labels['mh_title'] = 'Hoogtepunten van bericht';
$labels['mh_matches'] = 'komt overeen met';
$labels['mh_color'] = 'kleur';
$labels['mh_delete'] = 'verwijderen';
$labels['mh_delete_description'] = 'Verwijder deze regel';
$labels['mh_add'] = 'rij toevoegen';
$labels['mh_add_description'] = 'Voeg een extra rij toe onder deze rij';
$labels['deleteconfirm'] = 'Wil je deze regel echt verwijderen?';
$labels['headererror'] = 'Fout in berichtregel';
$labels['inputempty'] = 'Een of meer van je matches zijn leeg';
$labels['invalidcolor'] = 'Ongeldige kleur';
?>
