<?php
$labels = array();
$labels['mh_title'] = 'Høydepunkter i meldingen';
$labels['mh_matches'] = 'fyrstikker';
$labels['mh_color'] = 'farge';
$labels['mh_delete'] = 'slette';
$labels['mh_delete_description'] = 'Slett denne linjen';
$labels['mh_add'] = 'legg til rad';
$labels['mh_add_description'] = 'Legg til en ekstra rad under denne raden';
$labels['deleteconfirm'] = 'Vil du virkelig slette denne regelen?';
$labels['headererror'] = 'Feil i meldingsregel';
$labels['inputempty'] = 'En eller flere av fyrstikkene dine er tomme';
$labels['invalidcolor'] = 'Ugyldig farge';
?>
