<?php
$labels = array();
$labels['mh_title'] = 'Najważniejsze wiadomości';
$labels['mh_matches'] = 'mecze';
$labels['mh_color'] = 'kolor';
$labels['mh_delete'] = 'usunąć';
$labels['mh_delete_description'] = 'Usuń ten wiersz';
$labels['mh_add'] = 'dodać wiersz';
$labels['mh_add_description'] = 'Dodaj dodatkowy wiersz pod tym wierszem';
$labels['deleteconfirm'] = 'Czy naprawdę chcesz usunąć tę regułę?';
$labels['headererror'] = 'Błąd w regule wiadomości';
$labels['inputempty'] = 'Jedno lub więcej dopasowań jest pustych';
$labels['invalidcolor'] = 'Nieprawidłowy kolor';
?>
