<?php
$labels = array();
$labels['mh_title'] = 'د پیغام مهم ټکي';
$labels['mh_matches'] = 'مېچونه';
$labels['mh_color'] = 'رنګ';
$labels['mh_delete'] = 'مخکې';
$labels['mh_delete_description'] = 'دا کرښه حذف کړئ';
$labels['mh_add'] = 'قطار اضافه کړئ';
$labels['mh_add_description'] = 'د دې قطار لاندې یو اضافي قطار اضافه کړئ';
$labels['deleteconfirm'] = 'ایا تاسو رښتیا غواړئ دا قاعده حذف کړئ؟';
$labels['headererror'] = 'د پیغام په قاعده کې تېروتنه';
$labels['inputempty'] = 'ستاسو یو یا ډېر میچونه تش دي';
$labels['invalidcolor'] = 'غلط رنګ';
?>
