<?php
$labels = array();
$labels['mh_title'] = 'Destaques da mensagem';
$labels['mh_matches'] = 'jogos';
$labels['mh_color'] = 'cor';
$labels['mh_delete'] = 'excluir';
$labels['mh_delete_description'] = 'Excluir esta linha';
$labels['mh_add'] = 'adicionar linha';
$labels['mh_add_description'] = 'Adicione uma linha extra abaixo dessa linha';
$labels['deleteconfirm'] = 'Você realmente deseja excluir essa regra?';
$labels['headererror'] = 'Erro na regra de mensagem';
$labels['inputempty'] = 'Uma ou mais de suas correspondências estão vazias';
$labels['invalidcolor'] = 'Cor inválida';
?>
