<?php
$labels = array();
$labels['mh_title'] = 'Destaques da mensagem';
$labels['mh_matches'] = 'jogos';
$labels['mh_color'] = 'cor';
$labels['mh_delete'] = 'apagar';
$labels['mh_delete_description'] = 'Eliminar esta linha';
$labels['mh_add'] = 'adicionar linha';
$labels['mh_add_description'] = 'Adicionar uma linha extra por baixo desta linha';
$labels['deleteconfirm'] = 'Pretende mesmo eliminar esta regra?';
$labels['headererror'] = 'Erro na regra de mensagem';
$labels['inputempty'] = 'Uma ou mais das suas correspondências estão vazias';
$labels['invalidcolor'] = 'Cor inválida';
?>
