<?php
$labels = array();
$labels['mh_title'] = 'Mesaje importante';
$labels['mh_matches'] = 'meciuri';
$labels['mh_color'] = 'culoare';
$labels['mh_delete'] = 'ștergere';
$labels['mh_delete_description'] = 'Ștergeți această linie';
$labels['mh_add'] = 'adăugați rând';
$labels['mh_add_description'] = 'Adăugați un rând suplimentar sub acest rând';
$labels['deleteconfirm'] = 'Chiar doriți să ștergeți această regulă?';
$labels['headererror'] = 'Eroare în regula mesajului';
$labels['inputempty'] = 'Una sau mai multe dintre potrivirile dvs. sunt goale';
$labels['invalidcolor'] = 'Culoare invalidă';
?>
