<?php
$labels = array();
$labels['mh_title'] = 'Основные моменты сообщения';
$labels['mh_matches'] = 'соответствует';
$labels['mh_color'] = 'цвет';
$labels['mh_delete'] = 'удалить';
$labels['mh_delete_description'] = 'Удалите эту строку';
$labels['mh_add'] = 'добавить строку';
$labels['mh_add_description'] = 'Добавьте дополнительный ряд под этим рядом';
$labels['deleteconfirm'] = 'Вы действительно хотите удалить это правило?';
$labels['headererror'] = 'Ошибка в правиле сообщения';
$labels['inputempty'] = 'Одно или несколько ваших совпадений пустые';
$labels['invalidcolor'] = 'Недопустимый цвет';
?>
