<?php
$labels = array();
$labels['mh_title'] = 'Najdôležitejšie správy';
$labels['mh_matches'] = 'zodpovedá';
$labels['mh_color'] = 'farba';
$labels['mh_delete'] = 'vymazať';
$labels['mh_delete_description'] = 'Vymažte tento riadok';
$labels['mh_add'] = 'pridať riadok';
$labels['mh_add_description'] = 'Pridanie ďalšieho riadku pod tento riadok';
$labels['deleteconfirm'] = 'Naozaj chcete toto pravidlo vymazať?';
$labels['headererror'] = 'Chyba v pravidle správy';
$labels['inputempty'] = 'Jedna alebo viacero vašich zápaliek je prázdnych';
$labels['invalidcolor'] = 'Neplatná farba';
?>
