<?php
$labels = array();
$labels['mh_title'] = 'Poudarki sporočila';
$labels['mh_matches'] = 'se ujema z';
$labels['mh_color'] = 'barva';
$labels['mh_delete'] = 'izbriši';
$labels['mh_delete_description'] = 'Izbrišite to vrstico';
$labels['mh_add'] = 'dodajte vrstico';
$labels['mh_add_description'] = 'Dodajte dodatno vrstico pod to vrstico';
$labels['deleteconfirm'] = 'Ali res želite izbrisati to pravilo?';
$labels['headererror'] = 'Napaka v pravilu sporočila';
$labels['inputempty'] = 'Ena ali več vaših zadetkov je praznih';
$labels['invalidcolor'] = 'Neveljavna barva';
?>
