<?php
$labels = array();
$labels['mh_title'] = 'Pikat kryesore të mesazhit';
$labels['mh_matches'] = 'ndeshje';
$labels['mh_color'] = 'ngjyrë';
$labels['mh_delete'] = 'Fshi';
$labels['mh_delete_description'] = 'Fshi këtë rresht';
$labels['mh_add'] = 'Shto rresht';
$labels['mh_add_description'] = 'Shto një rresht shtesë nën këtë rresht';
$labels['deleteconfirm'] = 'A dëshironi me të vërtetë të fshini këtë rregull?';
$labels['headererror'] = 'Gabim në rregullën e mesazhit';
$labels['inputempty'] = 'Një ose më shumë nga përputhjet tuaja janë bosh';
$labels['invalidcolor'] = 'Ngjyrë e pavlefshme';
?>
