<?php
$labels = array();
$labels['mh_title'] = 'Истакнуте тачке поруке';
$labels['mh_matches'] = 'утакмице';
$labels['mh_color'] = 'боја';
$labels['mh_delete'] = 'избриши';
$labels['mh_delete_description'] = 'Избришите овај ред';
$labels['mh_add'] = 'додај ред';
$labels['mh_add_description'] = 'Додајте додатни ред испод овог реда';
$labels['deleteconfirm'] = 'Да ли заиста желите да избришете ово правило?';
$labels['headererror'] = 'Грешка у правилу за поруке';
$labels['inputempty'] = 'Једна или више ваших утакмица су празне';
$labels['invalidcolor'] = 'Неважећа боја';
?>
