<?php
$labels = array();
$labels['mh_title'] = 'Sammanfattning av meddelandet';
$labels['mh_matches'] = 'tändstickor';
$labels['mh_color'] = 'färg';
$labels['mh_delete'] = 'radera';
$labels['mh_delete_description'] = 'Ta bort denna rad';
$labels['mh_add'] = 'lägg till rad';
$labels['mh_add_description'] = 'Lägg till en extra rad under denna rad';
$labels['deleteconfirm'] = 'Vill du verkligen ta bort den här regeln?';
$labels['headererror'] = 'Fel i meddelanderegeln';
$labels['inputempty'] = 'En eller flera av dina matchningar är tomma';
$labels['invalidcolor'] = 'Ogiltig färg';
?>
