<?php
$labels = array();
$labels['mh_title'] = 'செய்திச் சிறப்பம்சங்கள்';
$labels['mh_matches'] = 'பொருந்துகின்றன';
$labels['mh_color'] = 'வண்ணம்';
$labels['mh_delete'] = 'நீக்கவும்';
$labels['mh_delete_description'] = 'இந்த வரியை நீக்கவும்';
$labels['mh_add'] = 'வரிசை சேர்';
$labels['mh_add_description'] = 'இந்த வரிக்குக் கீழே ஒரு கூடுதல் வரிசையைச் சேர்க்கவும்';
$labels['deleteconfirm'] = 'இந்த விதியை நீக்க நீங்கள் உண்மையிலேயே விரும்புகிறீர்களா?';
$labels['headererror'] = 'செய்தி விதியிலுள்ள பிழை';
$labels['inputempty'] = 'உங்கள் ஒன்று அல்லது அதற்கு மேற்பட்ட பொருத்துதல்கள் காலியாக உள்ளன.';
$labels['invalidcolor'] = 'செயலற்ற நிறம்';
?>
