<?php
$labels = array();
$labels['mh_title'] = 'ไฮไลต์ของข้อความ';
$labels['mh_matches'] = 'ตรงกัน';
$labels['mh_color'] = 'สี';
$labels['mh_delete'] = 'ลบ';
$labels['mh_delete_description'] = 'ลบบรรทัดนี้';
$labels['mh_add'] = 'เพิ่มแถว';
$labels['mh_add_description'] = 'เพิ่มแถวเพิ่มเติมใต้แถวนี้';
$labels['deleteconfirm'] = 'คุณต้องการจะลบกฎนี้จริง ๆ หรือไม่';
$labels['headererror'] = 'ข้อผิดพลาดในกฎการตรวจสอบข้อความ';
$labels['inputempty'] = 'หนึ่งหรือมากกว่าหนึ่งคู่ของคุณว่างเปล่า';
$labels['invalidcolor'] = 'สีไม่ถูกต้อง';
?>
