<?php
$labels = array();
$labels['mh_title'] = 'Öne Çıkan Mesajlar';
$labels['mh_matches'] = 'eşleşmeler';
$labels['mh_color'] = 'renk';
$labels['mh_delete'] = 'silme';
$labels['mh_delete_description'] = 'Bu satırı silin';
$labels['mh_add'] = 'satır ekle';
$labels['mh_add_description'] = 'Bu satırın altına fazladan bir satır ekleyin';
$labels['deleteconfirm'] = 'Bu kuralı gerçekten silmek istiyor musunuz?';
$labels['headererror'] = 'Mesaj kuralında hata';
$labels['inputempty'] = 'Eşleşmelerinizden biri veya daha fazlası boş';
$labels['invalidcolor'] = 'Geçersiz renk';
?>
