<?php
$labels = array();
$labels['mh_title'] = 'Основні моменти повідомлення';
$labels['mh_matches'] = 'сірники';
$labels['mh_color'] = 'колір';
$labels['mh_delete'] = 'видалити';
$labels['mh_delete_description'] = 'Видаліть цей рядок';
$labels['mh_add'] = 'додати рядок';
$labels['mh_add_description'] = 'Додайте додатковий рядок під цим рядком';
$labels['deleteconfirm'] = 'Ви дійсно хочете видалити це правило?';
$labels['headererror'] = 'Помилка в правилі повідомлення';
$labels['inputempty'] = 'Одна або більше ваших сірників порожні';
$labels['invalidcolor'] = 'Неправильний колір';
?>
