<?php
$labels = array();
$labels['mh_title'] = 'پیغام کے اہم نکات';
$labels['mh_matches'] = 'میچز';
$labels['mh_color'] = 'رنگ';
$labels['mh_delete'] = 'مٹائیں';
$labels['mh_delete_description'] = 'اس لائن کو حذف کریں';
$labels['mh_add'] = 'قطار شامل کریں';
$labels['mh_add_description'] = 'اس قطار کے نیچے ایک اضافی قطار شامل کریں۔';
$labels['deleteconfirm'] = 'کیا آپ واقعی اس قاعدے کو حذف کرنا چاہتے ہیں؟';
$labels['headererror'] = 'پیغام کے قاعدے میں خرابی';
$labels['inputempty'] = 'آپ کے ایک یا زیادہ میچ خالی ہیں۔';
$labels['invalidcolor'] = 'غلط رنگ';
?>
