<?php
$labels = array();
$labels['mh_title'] = 'Xabar asosiy jihatlari';
$labels['mh_matches'] = 'mos keladi';
$labels['mh_color'] = 'rang';
$labels['mh_delete'] = 'o\'chirish';
$labels['mh_delete_description'] = 'Ushbu satrni o\'chirish';
$labels['mh_add'] = 'qator qo\'shish';
$labels['mh_add_description'] = 'Ushbu qator ostiga qo\'shimcha qator qo\'shing';
$labels['deleteconfirm'] = 'Siz haqiqatan ham bu qoidani o\'chirmoqchimisiz?';
$labels['headererror'] = 'Xabar qoidasida xato';
$labels['inputempty'] = 'Sizning mos keluvchilaringizdan biri yoki bir nechtasi bo\'sh';
$labels['invalidcolor'] = 'Noto\'g\'ri rang';
?>
