<?php
$labels = array();
$labels['mh_title'] = 'Điểm nổi bật của tin nhắn';
$labels['mh_matches'] = 'trận đấu';
$labels['mh_color'] = 'màu';
$labels['mh_delete'] = 'xóa';
$labels['mh_delete_description'] = 'Xóa dòng này';
$labels['mh_add'] = 'thêm hàng';
$labels['mh_add_description'] = 'Thêm một hàng bổ sung bên dưới hàng này';
$labels['deleteconfirm'] = 'Bạn có thực sự muốn xóa quy tắc này không?';
$labels['headererror'] = 'Lỗi trong quy tắc tin nhắn';
$labels['inputempty'] = 'Một hoặc nhiều kết quả khớp của bạn trống';
$labels['invalidcolor'] = 'Màu không hợp lệ';
?>
