<?php
$labels = array();
$labels['mh_title'] = '信息要点';
$labels['mh_matches'] = '赛事';
$labels['mh_color'] = '颜色';
$labels['mh_delete'] = '删去';
$labels['mh_delete_description'] = '删除这一行';
$labels['mh_add'] = '添加行';
$labels['mh_add_description'] = '在该行下方添加额外一行';
$labels['deleteconfirm'] = '你真的想删除这条规则吗？';
$labels['headererror'] = '信息规则中的错误';
$labels['inputempty'] = '一个或多个匹配项为空';
$labels['invalidcolor'] = '无效颜色';
?>
