<?php
$labels = array();
$labels['mh_title'] = '訊息重點';
$labels['mh_matches'] = '比賽';
$labels['mh_color'] = '顏色';
$labels['mh_delete'] = '刪除';
$labels['mh_delete_description'] = '刪除此行';
$labels['mh_add'] = '新增行';
$labels['mh_add_description'] = '在此行下方新增一列';
$labels['deleteconfirm'] = '您真的要刪除這項規則嗎？';
$labels['headererror'] = '訊息規則中的錯誤';
$labels['inputempty'] = '您的一個或多個匹配是空的';
$labels['invalidcolor'] = '無效的顏色';
?>
